
SET ECHO ON

--1 List the states that Obama won in 2012 that Clinton also won in 2016. Use intersect
SELECT STATE
FROM VOTE
WHERE YEAR = 2012 AND WINNER = 'OBAMA'
INTERSECT
SELECT STATE
FROM VOTE
WHERE YEAR = 2016 AND WINNER = 'CLINTON';

--2 List the states that McCain won in 2008 plus the states that Romney won in 2012. Use Union
SELECT STATE
FROM VOTE
WHERE YEAR = 2008 AND WINNER = 'MCCAIN'
UNION
SELECT STATE
FROM VOTE
WHERE YEAR = 2012 AND WINNER = 'ROMNEY';

--3 List the states Obama won in 2008 that Clinton also won in 2016. Use Union All
SELECT STATE
FROM VOTE
WHERE YEAR = 2012 AND WINNER = 'OBAMA'
UNION ALL
SELECT STATE
FROM VOTE
WHERE YEAR = 2016 AND WINNER = 'CLINTON';

--4 List the candidate name and number of states won by Clinton and Trump in 2016 Use Union.

SELECT 'CLINTON' AS Candidate, COUNT(DISTINCT STATE) AS States_Won
FROM VOTE
WHERE YEAR = 2016 AND WINNER = 'CLINTON'
UNION
SELECT 'TRUMP' AS Candidate, COUNT(DISTINCT STATE) AS States_Won
FROM VOTE
WHERE YEAR = 2016 AND WINNER = 'TRUMP';

--5 List the States that Obama won in 2008 that he did not win in 2012. Use minus

SELECT STATE
FROM VOTE
WHERE YEAR = 2008 AND WINNER = 'OBAMA'
MINUS 
SELECT STATE
FROM VOTE
WHERE YEAR = 2012 AND WINNER = 'OBAMA';

--6 List states won democratic candidates (Obama and Clinton) won in all three elections (2008, 2012, 2016). Use 2 Intersects.

SELECT STATE 
FROM VOTE
WHERE YEAR = 2008 AND WINNER IN ('OBAMA','CLINTON')
INTERSECT
SELECT STATE
FROM VOTE  
WHERE YEAR = 2012 AND WINNER IN ('OBAMA','CLINTON')  
INTERSECT  
SELECT STATE
FROM VOTE
WHERE YEAR = 2016 AND WINNER IN ('OBAMA','CLINTON');

--7 List the States that Obama won in 2008 and 2012, that Clinton did not win in 2016.
SELECT STATE
FROM VOTE
WHERE YEAR = 2008 AND WINNER = 'OBAMA'
INTERSECT
SELECT STATE
FROM VOTE
WHERE YEAR = 2012 AND WINNER = 'OBAMA'
MINUS
SELECT STATE
FROM VOTE
WHERE YEAR = 2016 AND WINNER = 'CLINTON';

--8 List all States won by a different candidate in 2008, 2012 and 2016. That is a state that was won by 3 different candidates. 
--Only show states (not winners).

SELECT STATE
FROM VOTE
WHERE STATE IN (SELECT STATE FROM VOTE WHERE YEAR = 2008
   INTERSECT 
   SELECT STATE FROM VOTE WHERE YEAR = 2012
   INTERSECT
   SELECT STATE FROM VOTE WHERE YEAR = 2016)
GROUP BY STATE
HAVING COUNT(DISTINCT WINNER) = 3;


SELECT STATE 
FROM VOTE
WHERE WINNER IN ('OBAMA','CLINTON') AND YEAR = 2008
INTERSECT
SELECT STATE
FROM VOTE  
WHERE WINNER IN ('OBAMA','CLINTON') AND YEAR = 2012
INTERSECT  
SELECT STATE
FROM VOTE
WHERE WINNER IN ('OBAMA','CLINTON') AND YEAR = 2016;

